apiVersion: v1
kind: Service
metadata:
  name: frontend-rrhh-service
  namespace: peopleportal
spec:
  selector:
    app: frontend-rrhh
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
